# Урок 6. Многоклассовая классификация.

Посмотрим на примере алгоритма логистической регрессии и метода опорных векторов, как работать с различными методами многоклассовой классификации.

### 1.
Вспомните датасет Wine. Загрузите его, разделите на тренировочную и тестовую выборки (random_state=17), используя только [9, 11, 12] признаки.

In [6]:
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
import pandas as pd

In [7]:
load_wine = load_wine()
load_wine.keys()

C:\Users\pc\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\datasets\base.py:241: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  target = np.empty((n_samples,), dtype=np.int)
C:\Users\pc\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\datasets\base.py:245: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [20]:
load_wine_df = pd.DataFrame(load_wine.data[:, :7:-2], columns=load_wine.feature_names[:7:-2])
load_wine_df.head(3)

proline   hue  proanthocyanins
0   1065.0  1.04             2.29
1   1050.0  1.05             1.28
2   1185.0  1.03             2.81

In [21]:
x_train, x_test, y_train, y_test = train_test_split(load_wine_df, load_wine.target, random_state = 17)

print(f'X_train shape: {x_train.shape}, y_train shape: {y_train.shape},\n'
      f'X_test shape: {x_test.shape}, y_test shape: {y_test.shape}')

X_train shape: (133, 3), y_train shape: (133,),
X_test shape: (45, 3), y_test shape: (45,)


In [36]:
lg = LogisticRegression(random_state=17)
lg_model = lg.fit(x_train, y_train)
lg_model_prediction = lg_model.predict(x_test)

accuracy = accuracy_score(y_test, lg_model_prediction)
print(f'Accuracy: {accuracy}')

Accuracy: 0.9111111111111111


C:\Users\pc\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\pc\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


**Задайте тип кросс-валидации с помощью StratifiedKFold: 5-кратная, random_state=17.**

In [27]:
from sklearn.model_selection import StratifiedKFold, cross_val_score

In [35]:
skf = StratifiedKFold(n_splits = 5, random_state= 17) # тут мы разбили выборку на 5 частей

### 2.
Обучите логистическую регрессию (LogisticRegression) с параметром C по умолчанию и random_state=17. Укажите гиперпараметр multi_class='ovr' - по умолчанию многие классификаторы используют именно его. С помощью cross_val_score сделайте кросс-валидацию (используйте объект skf) и выведите среднюю долю правильных ответов на ней (используйте функцию mean). Отдельно выведите долю правильных ответов на тестовой выборке.

In [43]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import numpy as np

In [44]:
clf = LogisticRegression(C = 1.0, multi_class='ovr', random_state = 17)
clf = clf.fit(x_train, y_train)
cvs = cross_val_score(clf, x_test, y_test, cv=skf)
print(cvs)
print(np.mean(cvs))


[1.         1.         0.88888889 1.         1.        ]
0.9777777777777779


C:\Users\pc\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\pc\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:670: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  test_folds = np.zeros(n_samples, dtype=np.int)
C:\Users\pc\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:442: DeprecationWarning: `np.in

### 3.
Обучите метод опорных векторов (SVC) с random_state=17 и остальными параметрами по умолчанию. Этот метод при мультиклассовой классификации также использует метод "ovr". Сделайте кросс-валидацию (используйте skf) и, как и в предыдущем пункте, выведите среднюю долю правильных ответов на ней. Отдельно выведите долю правильных ответов на тестовой выборке.

In [46]:
from sklearn.svm import SVC

In [51]:
clf_svc = SVC(random_state=17)
clf_svc = clf_svc.fit(x_train, y_train)
cvs = cross_val_score(clf_svc, x_test, y_test, cv=skf)
print(cvs)
print(np.mean(cvs))

[0.5        0.5        0.44444444 0.44444444 0.42857143]
0.46349206349206346


C:\Users\pc\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\pc\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:670: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  test_folds = np.zeros(n_samples, dtype=np.int)
C:\Users\pc\AppData\Local\Co

Как видно из полученной метрики, на тестовой выборке метод с гиперпараметрами по умолчанию работает явно намного хуже логистической регрессии. В целом, SVM достаточно плохо масштабируется на размер обучающего набора данных (как видно, даже с тремя признаками он работает не очень хорошо), но благодаря возможности выбора различных ядер (функций близости, которые помогают разделять данные) и другим гиперпараметрам SVM можно достаточно точно настроить под определенный вид данных. Подробнее на этом останавливаться в контексте данного урока не будем.

### 4.
Для предсказаний обеих моделей постройте матрицу ошибок (confusion matrix) и напишите, какие классы каждая из моделей путает больше всего между собой.

In [52]:
from sklearn.metrics import classification_report, confusion_matrix

In [53]:
conf_mtrx = confusion_matrix(y_test, clf_svc.predict(x_test))
conf_mtrx

array([[9, 0, 0],
       [9, 9, 1],
       [6, 5, 6]], dtype=int64)

In [55]:
print(classification_report(y_test, clf_svc.predict(x_test)))

              precision    recall  f1-score   support

           0       0.38      1.00      0.55         9
           1       0.64      0.47      0.55        19
           2       0.86      0.35      0.50        17

    accuracy                           0.53        45
   macro avg       0.62      0.61      0.53        45
weighted avg       0.67      0.53      0.53        45



Тут мы видим что модель путает первый класс и второй класс (вторая строчка 9 и 9). В третей строчке (6, 5, 6) модель путает все классы между собой. 

In [56]:
print(classification_report(y_test, clf.predict(x_test)))

              precision    recall  f1-score   support

           0       0.82      1.00      0.90         9
           1       0.90      1.00      0.95        19
           2       1.00      0.76      0.87        17

    accuracy                           0.91        45
   macro avg       0.91      0.92      0.91        45
weighted avg       0.92      0.91      0.91        45



In [54]:
conf_mtrx = confusion_matrix(y_test, clf.predict(x_test))
conf_mtrx

array([[ 9,  0,  0],
       [ 0, 19,  0],
       [ 2,  2, 13]], dtype=int64)

Тут мы видим что модель не путает ни один из классов, разброс между правильно классифицированными обьектами и нет очень большой.

### 5.
Для каждой модели выведите classification report.

In [61]:
print('Модель clf\n',classification_report(y_test, clf.predict(x_test)))
print('\nМодель clf_svc\n',classification_report(y_test, clf_svc.predict(x_test)))

Модель clf
               precision    recall  f1-score   support

           0       0.82      1.00      0.90         9
           1       0.90      1.00      0.95        19
           2       1.00      0.76      0.87        17

    accuracy                           0.91        45
   macro avg       0.91      0.92      0.91        45
weighted avg       0.92      0.91      0.91        45


Модель clf_svc
               precision    recall  f1-score   support

           0       0.38      1.00      0.55         9
           1       0.64      0.47      0.55        19
           2       0.86      0.35      0.50        17

    accuracy                           0.53        45
   macro avg       0.62      0.61      0.53        45
weighted avg       0.67      0.53      0.53        45

